## team_likable_jelly

### Description
Richard Alligier received his Ph.D. (2014) degree in Computer Science from the 'Institut National Polytechnique de Toulouse' (INPT), his engineer’s degree (IEEAC, 2010) from the french university of civil aviation (ENAC) and his M.Sc. (2010) in computer science from the University of Toulouse. He is currently assistant professor at the ENAC in Toulouse, France. David Gianazza received his two engineer degrees (1986, 1996) from the 'École Nationale de l’Aviation Civile' (ENAC) and his M.Sc. (1996) and Ph.D. (2004) in Computer Science from the 'Institut National Polytechnique de Toulouse' (INPT). He has obtained his HDR (a french post-doctoral degree similar to tenure) in 2016 from the INPT. He has held various positions in the french civil aviation administration, successively as an engineer in ATC operations, technical manager, and researcher. He is currently associate professor at the ENAC, Toulouse

### Rationale for participation
We have worked on a PhD thesis estimating mass ten years ago, but it was with a different usage in mind, it was not the actual mass, more like an 'equivalent mass' for trajectory prediction. Nonetheless, maybe we can use some of our knowledge/techniques on this problem, and it might be fun to play with a data set of actual masses

