project:
  type: website

website:
  title: "PRC Data Challenge"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - data.qmd
      - rankings.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

filters:
  - acronyms

acronyms:
  loa_title: "List of Acronyms"
  include_unused: false
  insert_loa: "end"
  insert_links: true
  id_prefix: "acronyms_"
  sorting: "alphabetical"
  non_existing: "key"
  # style: "long-short"
  loa_format: '`**{shortname}**: {longname}`{=raw}'
  loa_header_classes:
  - unnumbered
  fromfile:
    - _acronyms.yml


